version: "3.8"

services:
  app:
    image: portainer/portainer-ce:alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/data
    networks:
      proxy_apps:

volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
