version: "3.8"

services:
  app:
    image: portainer/portainer-ce:alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/data
    networks:
      proxy_apps:
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.schedule=${BACKUP_CRON_SCHEDULE:-0 0 3 * * *}"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.command=sh -c 'apk --no-cache add sqlite && sqlite3 /data/portainer.db \".backup /data/portainer.db.backup\"'"

volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
